import { CliOptions, Framework, ProjectType } from '../../types/index.js';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { promises as fsPromises } from 'fs';
import { getVersion } from './version.js';
import chalk from 'chalk';

const CONFIG_FILE = '.attunerc';

// Valid config flags for validation
// Note: Only boolean flags work in .attunerc. Options that require values
// (like --framework, --rules-path, --max-file-size) must be passed on CLI.
const VALID_CONFIG_FLAGS = new Set([
  // Output formats
  '--json', '--html', '--markdown', '--sarif',
  // Scan modes (mutually exclusive)
  '--lite', '--full', '--security', '--architecture', '--performance', '--testing',
  // Output options
  '--verbose', '--ignore-dev-deps', '--public-safe', '--silent-security',
  '--no-paths', '--redact-secrets', '--use-attuneignore', '--no-cache'
]);

/**
 * Parse a config file and return array of flags
 */
export function parseConfigFile(content: string): string[] {
  const lines = content.split('\n');
  const flags: string[] = [];

  for (const line of lines) {
    // Strip inline comments (e.g., "--lite # comment" -> "--lite")
    const withoutComment = line.split('#')[0].trim();
    // Skip empty lines and full-line comments
    if (!withoutComment || line.trim().startsWith('#')) {
      continue;
    }
    flags.push(withoutComment);
  }

  return flags;
}

/**
 * Validate a config flag
 */
export function isValidConfigFlag(flag: string): boolean {
  return VALID_CONFIG_FLAGS.has(flag);
}

/**
 * Get all valid config flags
 */
export function getValidConfigFlags(): string[] {
  return Array.from(VALID_CONFIG_FLAGS);
}

/**
 * Load and apply config file settings
 * Returns modified CliOptions with config applied
 */
export async function applyConfig(
  projectRoot: string,
  options: CliOptions,
  parseFn: (content: string) => string[] = parseConfigFile,
  getVersionFn: (content: string) => string | null = getConfigVersion,
  currentVersion: string = getVersion()
): Promise<CliOptions> {
  // Determine config file path
  let configPath: string | undefined;
  if (options.config === false) {
    // --no-config was passed, skip config file
    return options;
  } else if (typeof options.config === 'string') {
    // Explicit config path
    configPath = options.config;
  } else {
    // Default: look for .attunerc in project root
    configPath = join(projectRoot, CONFIG_FILE);
  }

  // Check if config file exists
  if (!configPath || !existsSync(configPath)) {
    return options;
  }

  try {
    const configContent = await fsPromises.readFile(configPath, 'utf-8');

    // Check for version in config file
    const configVersion = getVersion(configContent);

    if (configVersion && configVersion !== currentVersion) {
      const configMajorMinor = configVersion.split('.').slice(0, 2).join('.');
      const currentMajorMinor = currentVersion.split('.').slice(0, 2).join('.');

      if (configMajorMinor !== currentMajorMinor) {
        console.log(chalk.yellow(`\nℹ️  Config file from v${configVersion} - you may have stale suppressions`));
        console.log(chalk.gray(`   Run with --verbose to see full config details`));
      }
    }

    const configFlags = parseFn(configContent);

    // Validate and warn about unknown flags
    for (const flag of configFlags) {
      if (!VALID_CONFIG_FLAGS.has(flag)) {
        console.warn(chalk.yellow(`⚠️  Unknown flag in .attunerc: '${flag}'`));
        console.warn(chalk.yellow(`   Valid flags: ${Array.from(VALID_CONFIG_FLAGS).join(', ')}`));
      }
    }

    if (configFlags.length === 0) {
      return options;
    }

    // Parse config flags and apply to options
    // Command-line flags take precedence over config file
    return applyConfigFlags(configFlags, options);
  } catch (err) {
    console.error(chalk.yellow(`⚠️  Failed to read config file: ${err}`));
    throw err;
  }
}

/**
 * Extract version from config content
 */
function getConfigVersion(content: string): string | null {
  const versionMatch = content.match(/Generated by Attune v(\d+\.\d+\.\d+)/);
  return versionMatch ? versionMatch[1] : null;
}

/**
 * Apply parsed config flags to options
 */
function applyConfigFlags(configFlags: string[], options: CliOptions): CliOptions {
  // Track if user explicitly set any output format on CLI
  const userSetOutputFormat = options.json || options.html || options.markdown || options.sarif;

  const mergedOptions = { ...options };

  for (const flag of configFlags) {
    // Skip invalid flags
    if (!VALID_CONFIG_FLAGS.has(flag)) {
      continue;
    }

    // Output format flags: only apply from config if user didn't set any on CLI
    if (!userSetOutputFormat) {
      if (flag === '--json') mergedOptions.json = true;
      else if (flag === '--html') mergedOptions.html = true;
      else if (flag === '--markdown') mergedOptions.markdown = true;
      else if (flag === '--sarif') mergedOptions.sarif = true;
    }

    // Other flags: only apply if not already set on CLI
    if (flag === '--lite' && !options.lite) mergedOptions.lite = true;
    else if (flag === '--full' && !options.full) mergedOptions.full = true;
    else if (flag === '--security' && !options.security) mergedOptions.security = true;
    else if (flag === '--architecture' && !options.architecture) mergedOptions.architecture = true;
    else if (flag === '--performance' && !options.performance) mergedOptions.performance = true;
    else if (flag === '--testing' && !options.testing) mergedOptions.testing = true;
    else if (flag === '--verbose' && !options.verbose) mergedOptions.verbose = true;
    else if (flag === '--ignore-dev-deps' && !options.ignoreDevDeps) mergedOptions.ignoreDevDeps = true;
    else if (flag === '--public-safe' && !options.publicSafe) mergedOptions.publicSafe = true;
    else if (flag === '--silent-security' && !options.silentSecurity) mergedOptions.silentSecurity = true;
    else if (flag === '--no-paths' && !options.noPaths) mergedOptions.noPaths = true;
    else if (flag === '--redact-secrets' && !options.redactSecrets) mergedOptions.redactSecrets = true;
    else if (flag === '--no-cache' && options.cache !== false) mergedOptions.cache = false;
  }

  return mergedOptions;
}