import { promises as fsPromises, existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, resolve } from 'path';
import { getVersion } from './version.js';
import chalk from 'chalk';

const ATTUNE_VERSION = getVersion();
export const ATTUNE_DIR = '.attune';
export const REPORT_DIR = join(ATTUNE_DIR, 'reports');
const DEFAULT_ATTUNEIGNORE = `# Attune Ignore Patterns
# Add patterns to exclude from analysis
# One pattern per line, supports:
# - Exact paths: src/oldcode/
# - Glob patterns: **/*.test.ts
# - File extensions: *.log

node_modules/
dist/
build/
.git/
.env
*.lock
`;

const DEFAULT_ATTUNERC = `# Attune Configuration File
# Generated by Attune v${ATTUNE_VERSION}
# This file specifies default flags for attune analyze
# Lines starting with # are comments
# Each flag should be on its own line

# Output format (uncomment your preference)
# --json
# --html
# --markdown
# --sarif

# Default scan mode
--lite
# --full

# Include .attuneignore patterns (this is the default behavior)
--use-attuneignore

# Safety options for output
# --public-safe
# --no-paths
# --redact-secrets
`;

/**
 * Get default output path for report files
 */
export function getDefaultOutputPath(projectRoot: string, format: string): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const ext = format === 'json' ? 'json' : format === 'html' ? 'html' : format === 'sarif' ? 'sarif' : 'md';
  return join(projectRoot, REPORT_DIR, `attune-${timestamp}.${ext}`);
}

/**
 * Initialize Attune directories and config files
 * Returns true if this is first run
 */
export async function initializeAttune(projectRoot: string): Promise<boolean> {
  const attuneDir = join(projectRoot, ATTUNE_DIR);
  const reportsDir = join(projectRoot, REPORT_DIR);
  const ignoreFile = join(projectRoot, '.attuneignore');
  const configFile = join(projectRoot, '.attunerc');

  let isFirstRun = false;

  // Create .attune directory if needed
  if (!existsSync(attuneDir)) {
    mkdirSync(attuneDir, { recursive: true });
    console.log(chalk.gray(`   → Created ${ATTUNE_DIR}/`));
    isFirstRun = true;
  }

  // Create reports subdirectory
  if (!existsSync(reportsDir)) {
    mkdirSync(reportsDir, { recursive: true });
    console.log(chalk.gray(`   → Created ${REPORT_DIR}/`));
  }

  // Create .attuneignore if needed
  if (!existsSync(ignoreFile)) {
    writeFileSync(ignoreFile, DEFAULT_ATTUNEIGNORE, 'utf-8');
    console.log(chalk.gray(`   → Created .attuneignore`));
    isFirstRun = true;
  }

  // Create .attunerc if needed
  if (!existsSync(configFile)) {
    writeFileSync(configFile, DEFAULT_ATTUNERC, 'utf-8');
    console.log(chalk.gray(`   → Created .attunerc`));
    isFirstRun = true;
  }

  // Create .gitignore entry if in a git repo and .attuneignore exists
  const gitIgnoreFile = join(projectRoot, '.gitignore');
  if (existsSync(gitIgnoreFile)) {
    const gitIgnoreContent = readFileSync(gitIgnoreFile, 'utf-8');
    if (!gitIgnoreContent.includes(ATTUNE_DIR)) {
      writeFileSync(gitIgnoreFile, gitIgnoreContent + `\n${ATTUNE_DIR}/\n`, 'utf-8');
      console.log(chalk.gray(`   → Added ${ATTUNE_DIR}/ to .gitignore`));
    }
  }

  return isFirstRun;
}